### ISSUE TITLE
Invalid session ID

### ISSUE THREAD

**Issue by samjohnson1357** [PaulNobrega/etrader#1]
I'm getting an invalid session ID error when I run the code on my E*TRADE account.  Everything seems to work up until it's time to copy the code and bring it back into Python.

**Comment by PaulNobrega** [comment]
I can't replicate because i no longer have an etrade account.  If you step through it you can see if it correctly pulls the code from the page.  If it doesn't it's likely that they've made changes to the html of that page that need to be reflected in this code.
